#############################################################
#  1. Model Define Configs
#############################################################
ModelConfig:
  model_type: 'NextVladBERT'
  use_modal_drop: True #在训练过程中，对多模态特征的某一模态进行丢弃
  with_embedding_bn: False #对不同模态输入特征进行BN归一化
  modal_drop_rate: 0.3
  with_video_head: True #视频特征
  with_audio_head: True #音频特征
  with_text_head: True  #文本特征
  with_image_head: False # False #图片特征

  #视频特征(16384)
  video_head_type: 'NeXtVLAD' #'RawNeXtVLAD'
  video_head_params:
    nextvlad_cluster_size: 128
    groups: 16
    expansion: 2
    feature_size: 2048 #inception feature dim
    max_frames: 300

  #语音特征(1024)
  audio_head_type: 'NeXtVLAD'
  audio_head_params:
    nextvlad_cluster_size: 64
    groups: 16
    expansion: 2
    feature_size: 128 #vggfish feature dim
    max_frames: 300

  #文本特征(1024)
  text_head_type: 'BERT' #'TextCnn'
  text_head_params:
    bert_path: '../pretrained/bert'
  text_cnn_params:
    embed_num: 14769
    embed_dim: 300
    feature_dim: 1024
    kernel_num: 10
    kernel_sizes: [3,4,5]
    dropout: 0.5
    embedding_path: '/home/tione/notebook/pretrained'
    embedding_name: 'sgns.baidubaike.bigram-char'
    # bert_emb_encode_size: 1024
  
  #图片特征(2048)
  image_head_type: 'resnet_v2_50'
  image_head_params: {}


  #多模态特征融合方式
  fusion_head_type: 'SE'
  fusion_head_params:
    hidden1_size: 1024
    gating_reduction: 8 # reduction factor in se context gating
    drop_rate:
      video: 0.8
      audio: 0.5
      image: 0.5
      text: 0.5
      fusion: 0.8
    concat_feat_dim: 
      video: 32768 #16384
      audio: 1024
      image: 0
      text: 1024 
      fusion: 34816 #18432
  #tagging分类器参数
  tagging_classifier_type: 'LogisticModel'
  tagging_classifier_params:
    num_classes: 82 #标签数目, 按需修改
    input_dim:
      video: 1024
      audio: 1024
      image: 0
      text: 1024
      fusion: 1024
  late_fusion: True
    
#############################################################
#2. Optimizer & Train Configs
#############################################################
OptimizerConfig:
  optimizer: 'AdamOptimizer'
  optimizer_init_params: {}
  clip_gradient_norm: 1.0
  learning_rate_dict:
    video: 0.0001
    audio: 0.0001
    text: 0.00001 # mafp: 学习率太小了吧
    image: 0.0001
    classifier: 0.01
  loss_type_dict:
    tagging: "CrossEntropyLoss"
  max_step_num: 10000
  export_model_steps: 1000
  learning_rate_decay: 0.1
  start_new_model: True # 如果为True，重新训练； 如果False，则resume
  num_gpu: 1 # mafp: 可以在这里设置gpu个数
  log_device_placement: False
  gpu_allow_growth: True
  pretrained_model:
    text_pretrained_model: 'pretrained/bert/chinese_L-12_H-768_A-12/bert_model.ckpt'
    image_pretrained_model: 'pretrained/resnet_v2_50/resnet_v2_50.ckpt'
  train_dir: './checkpoints/tagging5k_temp' #训练模型保存目录,按需修改

#############################################################
#    3. DataSet Config
#############################################################
DatasetConfig:
  batch_size: 32
  shuffle: True
  train_raw_data_path: '/home/tione/notebook/dataset/tagging/GroundTruth/datafile/raw_train_good.txt'
  val_raw_data_path: '/home/tione/notebook/dataset/tagging/GroundTruth/datafile/raw_val_good.txt'
  test_raw_data_path: '/home/tione/notebook/dataset/videos/video_5k/test_5k/'
  train_data_path: '/home/tione/notebook/dataset/tagging/GroundTruth/datafile/train_resnet.txt'
  #train_data_path: '/home/tione/notebook/dataset/structuring/GroundTruth/datafile/train.txt'
  val_data_path: '/home/tione/notebook/dataset/tagging/GroundTruth/datafile/val_resnet.txt'
  #val_data_path: '/home/tione/notebook/dataset/structuring/GroundTruth/datafile/val.txt'
  test_data_path: '../dataset/videos/video_5k/test_5k/'
  test_feat_path: '../dataset/tagging/tagging_dataset_test_5k/'
  vocab_path: '../pretrained/bert/vocab.txt'
  label_id_path: '/home/tione/notebook/dataset/label_id.txt'
  bert_path: '../pretrained/bert'
  text_max_len: 256
  csv_path: './scripts/bert_finetune_data.csv'
  embedding_path: '/home/tione/notebook/pretrained'
  embedding_name: 'sgns.baidubaike.bigram-char'
  device: 'cuda'
